version: '3'

networks:
  ecommerce:
    driver: bridge
  ecommerce_elastic:
    driver: bridge


volumes:
  ecommerce_local_postgres_data: {}
  ecommerce_local_postgres_data_backups: {}
  ecommerce_local_elasticsearch_data: {}

services:
  django: &django
    build:
     context: .
     dockerfile: ./compose/local/django/Dockerfile
    image: ecommerce_local_django
    container_name:  ecommerce_local_django
    depends_on:
      - postgres
      - redis
      - elasticsearch
    volumes:
      - .:/app:z
    links:
      - elasticsearch:elasticsearch
    networks:
      - ecommerce_elastic
      - ecommerce
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'

    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ecommerce_production_postgres
    container_name: ecommerce_local_postgres
    volumes:
      - ecommerce_local_postgres_data:/var/lib/postgresql/data
      - ecommerce_local_postgres_data_backups:/backups
    networks:
      - ecommerce
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: ecommerce_local_redis

  celeryworker:
    <<: *django
    image: ecommerce_local_celeryworker
    container_name: ecommerce_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    networks:
      - ecommerce
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ecommerce_local_celerybeat
    container_name: ecommerce_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    networks:
      - ecommerce
    command: /start-celerybeat

  flower:
    <<: *django
    image: ecommerce_local_flower
    container_name: ecommerce_local_flower
    ports:
      - '5555:5555'
    networks:
      - ecommerce
    command: /start-flower

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    # 8.x
    environment:
    #    - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.watermark.low=97%
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - ecommerce_elastic
    volumes:
    - ecommerce_local_elasticsearch_data:/usr/share/elasticsearch/data
