# Generated by Django 4.2.7 on 2023-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text='\n           مشخص می کند که آیا این کاربر باید به عنوان فعال در نظر گرفته شود\n          .به جای حذف حساب\u200cها، این را لغو انتخاب کنید."\n            ',
                verbose_name="فعال",
            ),
        ),
    ]
