# Generated by Django 5.2.1 on 2025-06-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinventory",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "max_length": "the price must be between 0 and 999.99."
                },
                help_text="format: maximum price 999.99",
                max_digits=5,
                verbose_name="recommended retail price",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "max_length": "the price must be between 0 and 999.99."
                },
                help_text="format: maximum price 999.99",
                max_digits=5,
                verbose_name="sale price",
            ),
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="store_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "max_length": "the price must be between 0 and 999.99."
                },
                help_text="format: maximum price 999.99",
                max_digits=5,
                verbose_name="regular store price",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product_inventory",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock",
                to="product.productinventory",
            ),
        ),
    ]
